/* Fake Data Generation */
function capitalize(str, separators) {
    separators = separators || [ ' ' ];
    var regex = new RegExp('(^|[' + separators.join('') + '])(\\w)', 'g');
    return str.replace(regex, function(x) { return x.toUpperCase(); });
}

let fakeAccounts = [
    {
        name: capitalize(`Brennan Cormac`, [`-`, `'`, ` `]),
        id: parseInt(`4`),
        groupID: parseInt(`12`),
        groupName: `Central Davenport`,
        image: `https://64.media.tumblr.com/940cd7d53247eaf95a543d2fc02e484c/tumblr_p2j7yd83P81vz2ghao4_1280.jpg`,
        type: `character`,
        species: `meta`,
        face: `jonathan young`,
        pronouns: `he/him`,
        age: parseInt(`37`),
        ageClass: `30s`,
        relStatus: `single`.toLowerCase().replace(' ', '').replace('\'', ''),
        alias: `meriel`.toLowerCase().replace(' ', "").replace('\/', ""),
        memAge: parseInt(`29`),
        frequency: `every 1 to 2 weeks`,
        limits: `detailed, mature sexual content`,
        overview: `Brennan is a bit of a mess He had a rough go of it as a child and learned young to not count on anyone else- a mentality that's persisted to this day. Of course, being tossed into an underground meta fighting ring as a young adult hardly helped. He's got a twisted worldview as a result of this and, while he's incredibly intelligent and a gifted forensic toxicologist, he finds it all a little dull.

        So, crime.

        He doesn't usually get his hands dirty, beyond quietly pulling aside people no one will miss to try out his personally-made poisons for his private research, but he's extremely adept at finding and gathering information and so offers these services on a for-hire basis. Mostly, he does this through a local criminal group known as the Zodiac, but he's done solo jobs as well on occasion.

        He doesn't tend to make friends very easily - a mix of aloofness and his odd sense of humour - and his loyalty is even harder won without a significant handful of cash. He's perfectly capable of a civil, and even friendly, conversation though - just be aware he's habitually nocturnal, so don't expect to see him in the middle of the day.`,
        imagePos: `center`,
        rawAlias: `meriel`,
    },
    {
        imagePos: `center`,
        rawAlias: `lux`,
        name: capitalize(`Cynbel Edevane`, [`-`, `'`, ` `]),
        alias: `lux`.toLowerCase().replace(' ', "").replace('\/', ""),
        memAge: parseInt(`29`),
        frequency: `every 1 to 2 weeks`,
        limits: `detailed, mature sexual content`,
        groupID: parseInt(`13`),
        id: parseInt(`43`),
        groupName: `Outskirts`,
        pronouns: `he/him`,
        face: `ezra miller`,
        overview: `Cynbel is your local vampiric asshole. He's proud, pretentious, and way too vain to let himself be seen as anything less that what he strictly dictates. He watches his image carefully, portraying the sides he wants people to see - often a little more violent and aggressive than most would find appropriate, but it keeps them all at arms length , which is part of the goal. He has mellowed a bit over the many centuries he's been alive, but he still isn't particularly benign as far as immortal beings go. He kills when he gets bored, he steals years off people's lives when he feels like it, and is a general gem of a creature (note the sarcasm). He has such a hard time relying on and trust people that he tends to avoid getting remotely close to people - especially people who are not immortal. He has had very few friends and is fairly determined to say he doesn't have (and has never had) any. He's still super bitter over the last time people he trusted fucked him over. And the time before that. And the time before that. Needless to say, he holds a grudge well, but he also hasn't been given any reason to trust. As for romance and intimacy, Cyn has had flings off and on over the years, but nothing too serious except when he came close to love with Mary Jane Kelly (his last Ripper victim). With his extreme sensitivity to pheromones and heartbeats, he's very picky about who he even considers a fling with and so he hasn't had a lot of them and a serious relationship would be a million times tougher to finagle out of him.`,
        type: `character`,
        age: parseInt(`2082`),
        ageClass: `immortal`,
        relStatus: `single`.toLowerCase().replace(' ', '').replace('\'', ''),
        species: `meta`,
        image: `https://64.media.tumblr.com/76440e43cbdc87b1116196f37849f222/511317c6596bdf04-c7/s1280x1920/c37af67e6d9094490a1e5152193582f8a70c98ae.jpg`,
    },
    {
        imagePos: `center`,
        rawAlias: `lux`,
        name: capitalize(`Hayden Donovan`, [`-`, `'`, ` `]),
        alias: `lux`.toLowerCase().replace(' ', "").replace('\/', ""),
        memAge: parseInt(`29`),
        frequency: `every 1 to 2 weeks`,
        limits: `detailed, mature sexual content`,
        groupID: parseInt(`10`),
        id: parseInt(`2`),
        groupName: `Coastline`,
        pronouns: `she/her`,
        face: `milla jovovich`,
        overview: `Hayden is... well, complicated but not at the same time. She's pretty straightforward to understand: she's ready to fuck you up if you fuck up her or people she cares about, and she's 100% capable of doing it. Don't bother her, she won't bother you, most likely — kind of like a hive of bees. Jostle her a little too much and you'll regret it. She's got a lot of pent up rage and anger over her mistreatment, especially given she believes the government was involved and she served and trusted them. It was enough to get her to start a whole damned rebellion, which is probably not what the metas need when the world just found out they exist but... well. Here we are anyway. Needless to say, getting on her bad side is... not recommended. If you're on her good side, though, no need to worry; she's a bit abrasive at times, but she's steady, reliable, and loyal to a fault.

        Speaking of that rebellion, she sort of knows everyone through either that or her work. She started off tending the bar at the Heart & Crown pub and bar on the coastline, which has become the main hub for rebellion meetings and activity. This to say, if she didn't meet someone through the rebellion, then she's probably served them drinks at some point. The Heart & Crown is more or less a public institution in Divine.`,
        type: `character`,
        age: parseInt(`28`),
        ageClass: `20s`,
        relStatus: `single`.toLowerCase().replace(' ', '').replace('\'', ''),
        species: `meta`,
        image: `https://64.media.tumblr.com/52e0b2b5d8df16be2906747ffd8c6b6a/d11abbca8359c565-2a/s640x960/caa2500dd4329fe1674806e9bbcaf0375ccefa27.jpg`,
    },
    {
        imagePos: `center`,
        rawAlias: `lux`,
        name: capitalize(`Jesse Dunn`, [`-`, `'`, ` `]),
        alias: `lux`.toLowerCase().replace(' ', "").replace('\/', ""),
        memAge: parseInt(`29`),
        frequency: `every 1 to 2 weeks`,
        limits: `detailed, mature sexual content`,
        groupID: parseInt(`13`),
        id: parseInt(`50`),
        groupName: `Outskirts`,
        pronouns: `he/him`,
        face: `viggo mortenson`,
        overview: `A cowboy who never quite outgrew the wild west and the call of the wide open plains, Jes is a bit rough-and-tumble and more likely to get into a fist fight than he is to calmly talk any sort of argument through. He's the passionate sort, and not in the slightest bit quiet, so has often been described as dramatic, overbearing, and reactive. It leads, frequently, to the assumption that he can't keep a secret to save his life, considering he never seems to shut up - but that's just a common misconception. He's remarkably good at shutting his trap when he's got to, or talking circles around the question until you don't know what you were asking any longer. It comes from a place of deep self-loathing that he's only partly gotten past, but hey, at least he talks about it now. To Gaius, specifically, because fuck if he's going to get all weepy to people that aren't his husband. He has his pride to maintain!`,
        type: `character`,
        age: parseInt(`239`),
        ageClass: `immortal`,
        relStatus: `married`.toLowerCase().replace(' ', '').replace('\'', ''),
        species: `meta`,
        image: `https://64.media.tumblr.com/a2ef7dbf678361d0c594fb7e8f1c5833/af990ad6c68dd970-ff/s1280x1920/93d23a77350f93249a804acde644987bf29c1ef6.jpg`,
    },
    {
        imagePos: `center`,
        rawAlias: `lux`,
        name: capitalize(`Madison McKinley`, [`-`, `'`, ` `]),
        alias: `lux`.toLowerCase().replace(' ', "").replace('\/', ""),
        memAge: parseInt(`29`),
        frequency: `every 1 to 2 weeks`,
        limits: `detailed, mature sexual content`,
        groupID: parseInt(`10`),
        id: parseInt(`45`),
        groupName: `Coastline`,
        pronouns: `she/her`,
        face: `tessa thompson`,
        overview: `Mads is general a sweet girl; she's the sort to bake cookies for new neighbours and offer up somewhat lewd jokes in the same breath, sure, but she's sweet and she means well. She's also, however, incredibly bullheaded and, once she sets her mind to something, it's near-impossible to get her to change it. She faces danger and sorrow both with a smile, determined not to let it get to her. It does, if she's honest, but fuck if she's telling anyone except those she's closest too - and, after her fiance went missing, that's precious few. Half of that is because she's currently undercover in the Order and, well, trusting the enemy is not something that comes highly recommended - but the other half? Intentional, trying to avoid feeling that hurt again. She'd rather stay a sunshine child, thanks.`,
        type: `character`,
        age: parseInt(`32`),
        ageClass: `30s`,
        relStatus: `single`.toLowerCase().replace(' ', '').replace('\'', ''),
        species: `meta`,
        image: `https://64.media.tumblr.com/9c96a8764436d70db5d4eb8fd1276976/dc6ed113a363f70d-e1/s640x960/77d774ca4ef4e0c63b3f8d5763bad0ac9cc8244f.jpg`,
    },
    {
        imagePos: `center`,
        rawAlias: `lux`,
        name: capitalize(`Malcolm Murdock`, [`-`, `'`, ` `]),
        alias: `lux`.toLowerCase().replace(' ', "").replace('\/', ""),
        memAge: parseInt(`29`),
        frequency: `every 1 to 2 weeks`,
        limits: `detailed, mature sexual content`,
        groupID: parseInt(`11`),
        id: parseInt(`3`),
        groupName: `Old Town`,
        pronouns: `he/him`,
        face: `timur simakov`,
        overview: `Malcolm is practically an urban legend around Davenport; he's a story that parents tell their children at night to keep them in their rooms and not climbing out of windows, and he's the monster under your bed. Not literally, of course. If you were to meet him on the streets, you'd likely look down on him. He's not particularly tall or short, a little on the scrawny side, and altogether a bit unassuming. The limp in his step, gloves over his hands, and generally calculating look in his eye, though, is what gives him away. He grew up on the streets and he is dead set on owning them - no matter the cost. The fact he's an upstart kid that came from out of nowhere only adds to his reputation.

        Malcolm is not only selective about those he associates with, but also his friends - especially his friends. He doesn't trust easily and he's more liable to play nice and stab you in the back than he is to actually be nice to you for the sake of being nice. This makes for a lot of fake friendships, or friendships based solely on convenience (if you can call either of those things a friendship). He didn't come to be called 'bastard' by most of the people in the seedy underbelly of Davenport by the age of sixteen through hugs and cupcakes and rainbows. No, he got there by being cruel, unforgiving, sadistic, and callous towards almost everyone. He steals, he murders, he ruins the plans of other criminals if there's something in it for him, and he's incredibly self-assured and self-centred. Basically, there is every reason to hate this guy on principle alone. And, honestly, he encourages it. Gimme those antagonistic plots up the wazoo (but also some people he's on good terms with because he will be awkward and won't know what to do).

        (And yes, he is 10000% a Kaz Brekker. As if that wasn't obvious to anyone who knows SoC).`,
        type: `character`,
        age: parseInt(`22`),
        ageClass: `20s`,
        relStatus: `single`.toLowerCase().replace(' ', '').replace('\'', ''),
        species: `meta`,
        image: `https://64.media.tumblr.com/289e7830f83c0545498ba6ae4333c1ca/tumblr_p3wz67wAPP1vz2ghao8_640.jpg`,
    },
    {
        imagePos: `center`,
        rawAlias: `lux`,
        name: capitalize(`Nikolas Kovac`, [`-`, `'`, ` `]),
        alias: `lux`.toLowerCase().replace(' ', "").replace('\/', ""),
        memAge: parseInt(`29`),
        frequency: `every 1 to 2 weeks`,
        limits: `detailed, mature sexual content`,
        groupID: parseInt(`10`),
        id: parseInt(`35`),
        groupName: `Coastline`,
        pronouns: `he/him`,
        face: `jack savoretti`,
        overview: `Nik is kind of a walking tragedy, to be quite honest. He's had a really hard life, and being immortal hasn't really helped much, because it's given him even more time to experience these hardships. He's a sensitive soul, feeling each of these things very deeply and to extremes, despite his attempts to shove all those feelings down. He is kind, though, and unerringly so. He will attempt to help just about anyone who needs it, even at great personal risk or cost to his own well-being. You'll find he can be quite distant at first if he doesn't know you. He is quite cautious, despite his desire to help and heal, and so will take a while to warm up, but he's trying to work on it.

        When it comes to interacting with people, he's particularly soft-spoken, but an otherwise excellent conversationalist (assuming you can get him to speak). He's easily distracted, often getting caught up in a flurry of his own thoughts and ideas, but trust that he hasn't missed a word you're saying either (at least, usually). He just might take a second or two to catch up and backtrack to what you were talking about first. Most of the people he knows, he knows through his work as a professor at the local university, but he may have some old friends from his time at Quantum - before he found out what they were doing and promptly left, but was too chicken to actually pursue any sort of action to stop them.`,
        type: `character`,
        age: parseInt(`199`),
        ageClass: `immortal`,
        relStatus: `single`.toLowerCase().replace(' ', '').replace('\'', ''),
        species: `meta`,
        image: `https://64.media.tumblr.com/e1a7a0df7663a3f06b0afb090871cfa1/e9564d2ab94005ea-93/s1280x1920/52dfbaf19a3e726bece2a45ce3f9c95a4fcd1662.jpg`,
    },
    {
        imagePos: `center`,
        rawAlias: `lux`,
        name: capitalize(`Satiah El Masry`, [`-`, `'`, ` `]),
        alias: `lux`.toLowerCase().replace(' ', "").replace('\/', ""),
        memAge: parseInt(`29`),
        frequency: `every 1 to 2 weeks`,
        limits: `detailed, mature sexual content`,
        groupID: parseInt(`11`),
        id: parseInt(`15`),
        groupName: `Old Town`,
        pronouns: `she/her`,
        face: `imaan hammam`,
        overview: `Tia is a spitfire of a woman, though you wouldn't always know it. Her abilities were awoken by someone who claimed to be the Egyptian god Anubis when she was younger and seeking revenge for the senseless murder of her daughter and her husband. One of these gifts was the ability to shift into a striped hyena, which has distinctly rubbed off on her, leaving her with a fair few tendencies of said animal. She is irrevocably nocturnal, lazing about during the day as best she can despite working, she has a stomach of steel and will eat anything, and her hearing is kind of shit. That said, she likes loud parties, bright lights, and late nights and she loves a good night club where she can get all three. She knows how to have a good time, and she isn't afraid to show it. Attachments really aren't her thing, unless she knows you're a fellow immortal, but she's rather content to hang out nonetheless.`,
        type: `character`,
        age: parseInt(`2173`),
        ageClass: `immortal`,
        relStatus: `single`.toLowerCase().replace(' ', '').replace('\'', ''),
        species: `meta`,
        image: `https://64.media.tumblr.com/43f5bf16f500a8ce1c48e7a4b86958aa/tumblr_pyloafSHEF1vz2ghao10_1280.jpg" style="object-position: top;`,
    },
    {
        imagePos: `center`,
        rawAlias: `lux`,
        name: capitalize(`Sterling Di Mitri`, [`-`, `'`, ` `]),
        alias: `lux`.toLowerCase().replace(' ', "").replace('\/', ""),
        memAge: parseInt(`29`),
        frequency: `every 1 to 2 weeks`,
        limits: `detailed, mature sexual content`,
        groupID: parseInt(`9`),
        id: parseInt(`36`),
        groupName: `River's Edge`,
        pronouns: `he/him`,
        face: `max barczak`,
        overview: `Honestly... Sterling is a bit of a mess. He spent his whole childhood doing everything he could to make his mother happy, not understanding that it was depression rather than regular sadness that plagued her, and after seeing her kill herself in a particularly low point, he's been stuck on that mindset ever since. He's determined to never ever cause problems and do whatever he has to to make other people happy, even at his own expense (and usually at his own expense, historically speaking). He even got so far as to propose to the girlfriend he has never had a single romantic feeling for last year just because they'd been together seven years and that was expected of him. In a panic, he ended up on a road trip across the country to move to Davenport and change universities, which sparked some of the real him and also gave him the chance to run into someone he actually had feelings for. And he's kind of been in a state of gay panic ever since.`,
        type: `character`,
        age: parseInt(`24`),
        ageClass: `20s`,
        relStatus: `single`.toLowerCase().replace(' ', '').replace('\'', ''),
        species: `meta`,
        image: `https://64.media.tumblr.com/b7566e3d90cf94f600c9fa2a92263538/c2c95cd4653a9c80-1b/s640x960/90f4f78d373132dddb075fddb78912cb01d74b38.jpg`,
    },
    {
        imagePos: `center`,
        rawAlias: ``,
        name: capitalize(`lux`, [`-`, `'`, ` `]),
        alias: ``.toLowerCase().replace(' ', "").replace('\/', ""),
        memAge: parseInt(`29`),
        memPronouns: `she/her`,
        frequency: `every 1 to 2 weeks`,
        limits: `detailed, mature sexual content`,
        groupID: parseInt(`4`),
        id: parseInt(`1`),
        groupName: `admin`,
        pronouns: ``,
        face: ``,
        overview: ``,
        type: `member`,
        age: parseInt(``),
        ageClass: ``,
        relStatus: ``.toLowerCase().replace(' ', '').replace('\'', ''),
        species: ``,
        image: `https://dawneggleton.github.io/images/photo/eq/2017-despook4.jpg`,
    }
];
